### PR TITLE
Fix HotelDetail explosion when not images or facilities are provided

### LINKED ISSUE #54: App crashes when there are no hotel images
After trying to show a hotel listing based on `https://playground-api.windingtree.com/hotels?limit=5&fields=id,name,description,images&startWith=0x02912E39927847de44f7dfBB11e216ebC81764f3` API call, the app crashes.

I think it's due to this hotel that is missing some (not required) fields. And I think the problem is mising the images field altogether.

```
{
description: "Subhajit Hotel"
id: "0x02912E39927847de44f7dfBB11e216ebC81764f3"
name: "Subhajit Hotel"
}
```

```
vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39 TypeError: Cannot read property '0' of undefined
    at f (app~d0ae3f07.9ef580766251beb5b5f9.js:1)
    at Li (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
    at ha (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
    at ma (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
    at Qa (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
    at Ya (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
    at $a (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
    at Va (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
    at ga (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
    at Object.enqueueSetState (vendors~app~9c5b28f6.9ef580766251beb5b5f9.js:39)
```

### PR DESCRIPTION
**Pull request by AceGentile**
when no images or facilities are provided (list is required for both AmenitiesList and ImageList components), avoid displaying them passing an undefined `list` prop since an array is require

this fixes #54

### CODE REVIEW

**Comment by JirkaChadima** [comment]
Also fixes #56

**Comment by JirkaChadima** [comment]
Thank you @AceGentile for fixing this!

**Comment by AugustoL** [comment]
thanks @AceGentile !

**Comment by AugustoL** [comment]
@AceGentile I just sent you a tip for your work, you can withdrawl it in gitcoin.co.

https://etherscan.io/tx/0x3e9a7046aa796cf89650d7c0ce6e67a30588ffe470a7c416cd1ea9e03d79a7be

**Pull request merged**
