### PR TITLE
Issue #9 environment add linter

### LINKED ISSUE #9: Environment: Add linter

### PR DESCRIPTION
**Pull request by PabloAlice**
fix #9

### CODE REVIEW

**Comment by PabloAlice** [comment]
Hello @JirkaChadima ! I cannot add reviewers at the moment, so I leave this comment here so you can check it out

**Comment by JirkaChadima** [comment]
Hey, what's the added value of this apart from commitizen config? The eslint was there before and I think the configuration really didn't change.

**Comment by PabloAlice** [comment]
Sure! 👌

**Comment by PabloAlice** [comment]
This PR was broken down in #13 #14

**Pull request closed without merging**
